### ISSUE TITLE
Steps required to upstream implementation

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#286]
Following last weeks meeting I think we are really close to be able to upstream our new implementation to core.

## Important Dates:

**March 13th**:

Date of next Modules meeting. Intent to approve implementation to be sent upstream

**March 20th**:

Date to open Pull request upstream to begin getting reviews

**March 27th**:

Date to review upstream concerns if necessary.

**April 4th**:

Target date to land upstream. Subject to change, could land sooner if no changes necessary.

**April 11th**:

Go / No Go date. If we cannot reach consensus upstream we will likely be unable to merge for 12.x after this date.

**April 23rd**:

Targeted release date for v12.x

## What needs to get done?

- [x] Finalize Phase 2 in [planning document](https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md) 
  - [x] loaders [#287](https://github.com/nodejs/modules/pull/287)
  - [x] extension / folder resolution #288 
- [x] implementation of missing phase two features
  - [x] Re add upstream loader [nodejs/ecmascript-modules#47](https://github.com/nodejs/ecmascript-modules/pull/47)  
  - [x] extensions / folder resolution [nodejs/ecmascript-module#48](https://github.com/nodejs/ecmascript-modules/pull/48)
- [x] Update Documentation to reflect latest implementation
  - [x] WIP [nodejs/ecmascript-modules#51](https://github.com/nodejs/ecmascript-modules/pull/51)
- [x] Final code + test + doc review
- [x] Determine messaging around upstream PR
- [x] Open Upstream PR
- [ ] Write copy about what our group has been doing and the current progress and status for public blog post

**Comment by MylesBorins** [comment]
If you have any thoughts or additions please chime in

**Comment by GeoffreyBooth** [comment]
I’m working on the docs update and I can help write the blog post copy (and be involved in messaging). I’ll need help with some of the sections of the docs, please let me know if anyone would like to help with this.

This might be a good time to start paying attention to our [project board](https://github.com/nodejs/modules/projects/6). 😄 (thanks @SMotaal)
